import { Router, type IRouter } from "express";

const router: IRouter = Router();

const RESOURCES = [
  {
    id: "bitcoin-whitepaper",
    title: "Bitcoin Whitepaper",
    description: "The original paper by Satoshi Nakamoto that started it all. Essential reading for understanding Bitcoin's design.",
    url: "https://bitcoin.org/bitcoin.pdf",
    category: "getting-started" as const,
  },
  {
    id: "bitcoin-org",
    title: "Bitcoin.org — Getting Started",
    description: "The official Bitcoin website with beginner guides, wallet recommendations, and how Bitcoin works.",
    url: "https://bitcoin.org/en/getting-started",
    category: "getting-started" as const,
  },
  {
    id: "kiwi-bitcoin-guide",
    title: "Kiwi Bitcoin Guide",
    description: "Our very own HGW's New Zealand-focused guide to using Bitcoin and connecting with the broader Bitcoin community in Aotearoa.",
    url: "https://kiwibitcoinguide.org/",
    category: "education" as const,
  },
  {
    id: "learn-me-a-bitcoin",
    title: "Learn Me a Bitcoin",
    description: "A beautifully illustrated technical guide to how Bitcoin works under the hood — from transactions to mining.",
    url: "https://learnmeabitcoin.com/",
    category: "education" as const,
  },
  {
    id: "phoenix",
    title: "Phoenix",
    description: "Self-custodial Lightning wallet for mobile",
    url: "https://phoenix.acinq.co/",
    category: "tools" as const,
    toolCategory: "Bitcoin Wallets",
  },
  {
    id: "sparrow-tool",
    title: "Sparrow",
    description: "Desktop Bitcoin wallet",
    url: "https://sparrowwallet.com/",
    category: "tools" as const,
    toolCategory: "Bitcoin Wallets",
  },
  {
    id: "nunchuk",
    title: "Nunchuk",
    description: "Multi-sig Bitcoin wallet with collaborative key management",
    url: "https://nunchuk.io/",
    category: "tools" as const,
    toolCategory: "Bitcoin Wallets",
  },
  {
    id: "wallet-of-satoshi",
    title: "Wallet of Satoshi",
    description: "Simple Lightning wallet for everyday Bitcoin payments",
    url: "https://www.walletofsatoshi.com/",
    category: "tools" as const,
    toolCategory: "Bitcoin Wallets",
  },
  {
    id: "bull-bitcoin-wallet",
    title: "Bull Bitcoin Wallet",
    description: "Non-custodial Bitcoin wallet with built-in exchange",
    url: "https://www.bullbitcoin.com/wallet",
    category: "tools" as const,
    toolCategory: "Bitcoin Wallets",
  },
  {
    id: "trezor",
    title: "Trezor",
    description: "The best combination of security and user experience in the Bitcoin hardware wallet space",
    url: "https://trezor.io/",
    category: "tools" as const,
    toolCategory: "Hardware Wallets",
  },
  {
    id: "coldcard",
    title: "ColdCard",
    description: "The best security of any Bitcoin hardware wallet in this space, hands down",
    url: "https://coldcard.com/",
    category: "tools" as const,
    toolCategory: "Hardware Wallets",
  },
  {
    id: "seedsigner",
    title: "SeedSigner",
    description: "If you're really, really hardcore about free and open source software and you want to make your own device — only recommended in a multi-sig setup, not as a single sig wallet",
    url: "https://seedsigner.com/",
    category: "tools" as const,
    toolCategory: "Hardware Wallets",
  },
  {
    id: "ppq",
    title: "PPQ",
    description: "An AI marketplace where you pay per query with access to all the top models. You only pay for what you use.",
    url: "https://ppq.ai/",
    category: "tools" as const,
    toolCategory: "Privacy Preserving AI",
    toolCategoryNote: "AI that can be paid for in Bitcoin, preserving your privacy and the ability for Evil Megacorps to create a profile of you.",
  },
  {
    id: "maple-ai",
    title: "Maple AI",
    description: "A privacy-first AI platform leveraging secure enclaves and only using open source models.",
    url: "https://trymaple.ai/",
    category: "tools" as const,
    toolCategory: "Privacy Preserving AI",
  },
  {
    id: "routstr",
    title: "Routstr",
    description: "Privacy-focused AI routing and inference",
    url: "https://routstr.com/",
    category: "tools" as const,
    toolCategory: "Privacy Preserving AI",
  },
  {
    id: "mullvad",
    title: "Mullvad",
    description: "No-logs VPN service",
    url: "https://mullvad.net/en",
    category: "tools" as const,
    toolCategory: "VPN",
    toolCategoryNote: "All accept Bitcoin — for maximum privacy, we highly recommend paying for your VPN service in Bitcoin.",
  },
  {
    id: "ivpn",
    title: "IVPN",
    description: "Privacy-focused VPN",
    url: "https://www.ivpn.net/en/",
    category: "tools" as const,
    toolCategory: "VPN",
  },
  {
    id: "obscura",
    title: "Obscura",
    description: "The most privacy-preserving VPN, though it runs slightly slower than the others. It was also created by a former Bitcoin Core contributor, so hey, there's that.",
    url: "https://obscura.net/",
    category: "tools" as const,
    toolCategory: "VPN",
  },
  {
    id: "start9",
    title: "Start9",
    description: "Sovereign home server & node",
    url: "https://start9.com/",
    category: "tools" as const,
    toolCategory: "Bitcoin Nodes",
  },
  {
    id: "umbrel",
    title: "Umbrel",
    description: "Personal home server for self-hosting apps and running a Bitcoin node",
    url: "https://umbrel.com/",
    category: "tools" as const,
    toolCategory: "Bitcoin Nodes",
  },
  {
    id: "parmanode",
    title: "Parmanode",
    description: "DIY Bitcoin node setup",
    url: "https://parmanode.com/",
    category: "tools" as const,
    toolCategory: "Bitcoin Nodes",
  },
  {
    id: "mempool-space",
    title: "Mempool.space",
    description: "Open-source Bitcoin blockchain explorer and mempool visualiser",
    url: "https://mempool.space/",
    category: "tools" as const,
    toolCategory: "Block Explorer",
  },
  {
    id: "blockstream-info",
    title: "Blockstream.info",
    description: "Bitcoin block explorer by Blockstream",
    url: "https://blockstream.info/",
    category: "tools" as const,
    toolCategory: "Block Explorer",
  },
  {
    id: "cmh-mempool",
    title: "CMH Mempool",
    description: "Cyphermunk House's block explorer (if you're ever in London, definitely visit Cyphermunk House — they're the best)",
    url: "https://cyphermunkhouse.angor.online/",
    category: "tools" as const,
    toolCategory: "Block Explorer",
  },
  {
    id: "nostr",
    title: "NOSTR",
    description: "Learn about the Nostr protocol",
    url: "https://nostr.com/",
    category: "tools" as const,
    toolCategory: "Nostr",
    toolCategoryNote: "A decentralized, censorship-resistant communications protocol... which might just work.",
  },
  {
    id: "primal",
    title: "Primal",
    description: "Nostr client with built-in Bitcoin Lightning wallet",
    url: "https://primal.net/",
    category: "tools" as const,
    toolCategory: "Nostr",
  },
  {
    id: "damus",
    title: "Damus",
    description: "Nostr client for iOS",
    url: "https://damus.io/",
    category: "tools" as const,
    toolCategory: "Nostr",
  },
  {
    id: "amethyst",
    title: "Amethyst",
    description: "Nostr client for Android",
    url: "https://nostrapps.com/amethyst",
    category: "tools" as const,
    toolCategory: "Nostr",
  },
  {
    id: "grapheneos",
    title: "GrapheneOS",
    description: "Privacy-focused alternative to Android",
    url: "https://grapheneos.org/",
    category: "tools" as const,
    toolCategory: "Mobile OS",
  },
  {
    id: "calyxos",
    title: "CalyxOS",
    description: "Privacy-focused Android alternative with built-in security features",
    url: "https://calyxos.org/",
    category: "tools" as const,
    toolCategory: "Mobile OS",
  },
  {
    id: "stacker-news",
    title: "Stacker News",
    description: "A community-driven Bitcoin news and discussion platform. Earn sats for posting and commenting on quality content.",
    url: "https://stacker.news/",
    category: "news" as const,
  },
  {
    id: "no-bs-bitcoin",
    title: "No BS Bitcoin",
    description: "Straightforward Bitcoin guides and reviews without the hype. Focused on practical, honest information for everyday users.",
    url: "https://www.nobsbitcoin.com/",
    category: "news" as const,
  },
  {
    id: "citadel-wire",
    title: "Citadel Wire",
    description: "Bitcoin-focused news aggregator covering the latest developments, analysis, and stories from around the Bitcoin ecosystem.",
    url: "https://citadelwire.com/",
    category: "news" as const,
  },
  {
    id: "the-bitcoin-standard",
    title: "The Bitcoin Standard (Book)",
    description: "By Saifedean Ammous — an exploration of the history of money and Bitcoin's role as sound money.",
    url: "https://saifedean.com/thebitcoinstandard/",
    category: "education" as const,
  },
];

router.get("/resources", (_req, res) => {
  res.json(RESOURCES);
});

export default router;
